from datetime import date, datetime

from sqlalchemy import BigInteger, Date, DateTime, DECIMAL, ForeignKey, Index, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin


class Supplier(Base, TimestampMixin):
    """
    Demo Supplier Enrichment Layer.

    The DataCo dataset has no real supplier master. This table holds
    DETERMINISTIC SYNTHETIC supplier metadata (fixed random seed), generated by
    scripts/feature_engineering.py::generate_supplier_master(). It is clearly
    labeled as synthetic in the UI (see frontend data-provenance badges) and in
    docs/data-pipeline.md. Never treat these as real companies.
    """

    __tablename__ = "suppliers"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    supplier_code: Mapped[str] = mapped_column(String(30), unique=True, nullable=False, index=True)
    supplier_name: Mapped[str] = mapped_column(String(150), nullable=False)
    supplier_region: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    supplier_tier: Mapped[str] = mapped_column(String(20), nullable=False)  # strategic/preferred/standard
    product_category: Mapped[str] = mapped_column(String(100), nullable=False, index=True)

    historical_lead_time_days: Mapped[float] = mapped_column(DECIMAL(6, 2), nullable=False)
    capacity_score: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False)
    quality_score: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False)
    reliability_score: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False)
    cost_score: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False)
    risk_score: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False)

    is_synthetic: Mapped[bool] = mapped_column(default=True, nullable=False)

    metrics: Mapped[list["SupplierMetric"]] = relationship(back_populates="supplier")


class SupplierMetric(Base, TimestampMixin):
    """
    Time-bucketed DERIVED supplier performance, computed from actual shipment
    history joined against the synthetic supplier assignment. Recomputed by
    the analytics job (app/analytics/supplier_scoring.py). One row per
    supplier per period (period_start = first day of month, by default).
    """

    __tablename__ = "supplier_metrics"
    __table_args__ = (
        Index("ix_supplier_metrics_supplier_period", "supplier_id", "period_start"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    supplier_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("suppliers.id", ondelete="CASCADE"), nullable=False, index=True
    )
    period_start: Mapped[date] = mapped_column(Date, nullable=False)

    order_volume: Mapped[int] = mapped_column(BigInteger, nullable=False, default=0)
    delay_rate: Mapped[float] = mapped_column(DECIMAL(6, 4), nullable=False, default=0)
    avg_lead_time_days: Mapped[float] = mapped_column(DECIMAL(6, 2), nullable=False, default=0)

    score: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False, index=True)
    reliability_component: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False, default=0)
    delivery_component: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False, default=0)
    quality_component: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False, default=0)
    lead_time_component: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False, default=0)
    cost_component: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False, default=0)
    risk_component: Mapped[float] = mapped_column(DECIMAL(5, 2), nullable=False, default=0)

    computed_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    supplier: Mapped["Supplier"] = relationship(back_populates="metrics")
