"""initial schema

Revision ID: e3dfae867b63
Revises: 
Create Date: 2026-09-01 10:15:18.146948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3dfae867b63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_customer_id', sa.BigInteger(), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('zipcode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_segment'), 'customers', ['segment'], unique=False)
    op.create_index(op.f('ix_customers_source_customer_id'), 'customers', ['source_customer_id'], unique=True)
    op.create_table('model_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_product_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=150), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=150), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_category_name'), 'products', ['category_name'], unique=False)
    op.create_index(op.f('ix_products_source_product_id'), 'products', ['source_product_id'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('root_causes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('factor_name', sa.String(length=100), nullable=False),
    sa.Column('contribution_pct', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('supporting_metric', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_root_causes_entity', 'root_causes', ['entity_type', 'entity_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('supplier_code', sa.String(length=30), nullable=False),
    sa.Column('supplier_name', sa.String(length=150), nullable=False),
    sa.Column('supplier_region', sa.String(length=100), nullable=False),
    sa.Column('supplier_tier', sa.String(length=20), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('historical_lead_time_days', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('capacity_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('quality_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('reliability_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('cost_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('risk_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_product_category'), 'suppliers', ['product_category'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=True)
    op.create_index(op.f('ix_suppliers_supplier_region'), 'suppliers', ['supplier_region'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_by', sa.BigInteger(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_severity_status', 'alerts', ['severity', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_order_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False),
    sa.Column('order_region', sa.String(length=100), nullable=False),
    sa.Column('order_country', sa.String(length=100), nullable=False),
    sa.Column('order_state', sa.String(length=100), nullable=False),
    sa.Column('order_city', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_market'), 'orders', ['market'], unique=False)
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_index(op.f('ix_orders_order_region'), 'orders', ['order_region'], unique=False)
    op.create_index(op.f('ix_orders_source_order_id'), 'orders', ['source_order_id'], unique=True)
    op.create_table('supplier_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('order_volume', sa.BigInteger(), nullable=False),
    sa.Column('delay_rate', sa.DECIMAL(precision=6, scale=4), nullable=False),
    sa.Column('avg_lead_time_days', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('reliability_component', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('delivery_component', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('quality_component', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('lead_time_component', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('cost_component', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('risk_component', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_metrics_score'), 'supplier_metrics', ['score'], unique=False)
    op.create_index(op.f('ix_supplier_metrics_supplier_id'), 'supplier_metrics', ['supplier_id'], unique=False)
    op.create_index('ix_supplier_metrics_supplier_period', 'supplier_metrics', ['supplier_id', 'period_start'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shipment_code', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('shipping_mode', sa.String(length=30), nullable=False),
    sa.Column('scheduled_shipping_days', sa.SmallInteger(), nullable=False),
    sa.Column('order_item_quantity', sa.Integer(), nullable=False),
    sa.Column('product_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('discount_rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('sales', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('order_profit_per_order', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('origin_market', sa.String(length=50), nullable=False),
    sa.Column('destination_region', sa.String(length=100), nullable=False),
    sa.Column('days_for_shipping_real', sa.SmallInteger(), nullable=False),
    sa.Column('delivery_status', sa.String(length=50), nullable=False),
    sa.Column('late_delivery_risk', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_destination_region'), 'shipments', ['destination_region'], unique=False)
    op.create_index(op.f('ix_shipments_late_delivery_risk'), 'shipments', ['late_delivery_risk'], unique=False)
    op.create_index(op.f('ix_shipments_order_date'), 'shipments', ['order_date'], unique=False)
    op.create_index('ix_shipments_order_date_mode', 'shipments', ['order_date', 'shipping_mode'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_product_id'), 'shipments', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipments_risk_level'), 'shipments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_shipments_risk_score'), 'shipments', ['risk_score'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_code'), 'shipments', ['shipment_code'], unique=True)
    op.create_index(op.f('ix_shipments_shipping_mode'), 'shipments', ['shipping_mode'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_supplier_id'), 'shipments', ['supplier_id'], unique=False)
    op.create_index('ix_shipments_supplier_risk', 'shipments', ['supplier_id', 'risk_level'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.Text(), nullable=False),
    sa.Column('confidence', sa.DECIMAL(precision=4, scale=3), nullable=False),
    sa.Column('supporting_metrics', sa.JSON(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_shipment', 'recommendations', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_recommendations_shipment_id'), 'recommendations', ['shipment_id'], unique=False)
    op.create_table('shipment_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('model_version_id', sa.BigInteger(), nullable=False),
    sa.Column('probability', sa.DECIMAL(precision=6, scale=5), nullable=False),
    sa.Column('risk_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_predictions_model_version_id'), 'shipment_predictions', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_shipment_predictions_shipment_id'), 'shipment_predictions', ['shipment_id'], unique=False)
    op.create_index('ix_shipment_predictions_shipment_model', 'shipment_predictions', ['shipment_id', 'model_version_id'], unique=False)
    op.create_table('shipment_risk_factors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.String(length=255), nullable=False),
    sa.Column('shap_value', sa.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['shipment_predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_factors_prediction_rank', 'shipment_risk_factors', ['prediction_id', 'rank'], unique=False)
    op.create_index(op.f('ix_shipment_risk_factors_prediction_id'), 'shipment_risk_factors', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE: hand-simplified from the raw autogenerate output. Autogenerate
    # emits an explicit op.drop_index() for every index before op.drop_table()
    # — but on MySQL/InnoDB, a composite index that also backs a foreign key
    # (e.g. shipment_risk_factors.ix_risk_factors_prediction_rank, which
    # covers the FK'd prediction_id column) can't be dropped independently
    # while the FK still references it ("Cannot drop index ... needed in a
    # foreign key constraint"). Dropping the table removes its indexes and
    # FKs together, so we rely on that instead — order still matters
    # (children before parents), which is preserved below.
    op.drop_table('shipment_risk_factors')
    op.drop_table('shipment_predictions')
    op.drop_table('recommendations')
    op.drop_table('shipments')
    op.drop_table('ai_messages')
    op.drop_table('user_roles')
    op.drop_table('supplier_metrics')
    op.drop_table('orders')
    op.drop_table('audit_logs')
    op.drop_table('alerts')
    op.drop_table('ai_conversations')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('root_causes')
    op.drop_table('roles')
    op.drop_table('products')
    op.drop_table('model_versions')
    op.drop_table('customers')
